{% set name = "pytest-icdiff" %}
{% set version = "0.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7cf5e75174f04f1e35c153e3b1e5759b33dbad0c914f1683a3d60175e10f7d1b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - icdiff
    - pprintpp
    - pytest
    - python >=3.6

test:
  imports:
    - pytest_icdiff

about:
  home: https://github.com/hjwp/pytest-icdiff
  license: GNU General Public v3
  license_family: GPL3
  license_file: LICENSE
  summary: use icdiff for better error messages in pytest assertions

extra:
  recipe-maintainers:
    - nicoddemus
