{% set name = "pytest-icdiff" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fedfddeaec1921f49c7edd4e2d3f5a584c0c13fb0d15c06a4d7e0b5542b63e35

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - icdiff
    - pprintpp
    - pytest
    - python >=3.6

test:
  imports:
    - pytest_icdiff

about:
  home: https://github.com/hjwp/pytest-icdiff
  license: GNU General Public v3
  license_family: GPL3
  license_file: LICENSE
  summary: use icdiff for better error messages in pytest assertions

extra:
  recipe-maintainers:
    - nicoddemus
