travis:
  secure:
    BINSTAR_TOKEN: uzyL5HJAxN88fZigV8F7uTkdKgv4359Y/2Uobd3GwJ+iSpvWfmhpXAbKuDJgYapAhQcFPazcF09DZ+OGmpiqrhTtP/M1VtZhVLMa4YU9rCLnpzfX+2g6n19XhR4iVzvBvYfNU5Yr4ErVM3fAB3HvuwBPghli1+QXGupYncCsXbNYU2nEs0Cxqlw5pk9uymHxfj6KS1CDxQuCY8UK2x2Q37XOwJDVPjooScj7gnEMfqqKMCsQiRdx3O00WZjZjCNRWasf1NCqlfp18VTg63eeTjJmd59dwz+0dLos7YcGxBUHxFEB+IhmlHILPR1wMWW6/v0h/FaawufsUB53NT0WXfDlGsP6G50nELZ90hhWrlMsq2tolE08b3peDOyxaA8Apmk02H5C/Z2g665wzDU0yv4YFzeM2QUstUtBJXqnn/F29Gqi5XP9xJ2GWYaLFtrNGaZLA8ekYLbFY1mBctHM1IGIoS1CJ7N5ovb+seFN0YZDjtslyWu6YTZnnaWNVShuX9enSDMHMFwwdw5txnVeWpR/kk43CkGOkjs9t2pr1T6UsDrzEh0jeFtBo9jm1S6IojGRFHZ9UHarWqJ/rkYlFSDI1JV9d7uIKugVzvEqx2ZyXPN/OxzDqlObEZRUV8y0PsN827rnr6WXRwTKVs/9E+q+nbl+DicsZs4a5XxtuQ4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
